# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: W1BTR.COMTray
PackageVersion: 1.0.0
InstallerType: wix
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/BigTimeRadio/COMTray/releases/download/v1.0.0/ComTray-1.0.0.msi
    InstallerSha256: 8AEAB592D210D2C5BD0E87FA0359776924668E7175C9566CD2512CF507E65084
    ProductCode: '{D20A77E2-2B7D-4FE5-A6F7-CFC96C7D40B8}'
ManifestType: installer
ManifestVersion: 1.6.0
