# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: W1BTR.COMTray
PackageVersion: 1.0.0
InstallerType: wix
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/BigTimeRadio/COMTray/releases/download/v1.0.0/ComTray-1.0.0.msi
    InstallerSha256: 7414E23740E9E1B640BEC6E505094470A5998EC8A2BA514F714473A6DBB202BB
    ProductCode: '{7831E1FD-0D3A-43CC-BBD5-0C69908DAA56}'
ManifestType: installer
ManifestVersion: 1.6.0
